### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-update-guide#17]

**Comment by StephenFluin** [comment]
@lacolaco if you want to create a translated version of recommendations.ts, I'd be happy to add the router so that you can point to update.angular.io/jp or something like that which loads the different set of recommendations.

Would that be enough or are you hoping for something further?

**Comment by lacolaco** [comment]
@StephenFluin perfect idea! A set of `update.angular.io/jp` and language selector is completely what I  want.

**Comment by StephenFluin** [comment]
@lacolaco Any luck creating a translated version of the recommendations?

**Comment by lacolaco** [comment]
@StephenFluin Of course! 
In my thought, I can add `app/locales/ja.ts`  and it will export an object map.

```
export const recommendations = {
  '<step key>': { /* localized step */ }
};
```

So I hope every step has its own key string or number. and I want localized version's component to display steps as a rule below:

1. Get all steps from English version
1. Look up its own locale's version for each step by its key.
  1. If it exists, show the localized version.
  1. It not, show the original English version.

How do you think?

**Comment by StephenFluin** [comment]
Sounds great!
