### ISSUE TITLE
Twice the same command from 8 to 9

### ISSUE THREAD

**Issue by GregoireLgt** [angular/angular-update-guide#176]
When you migrate from 8 to 9 there is twice the same command, not sure why ?

![image](https://user-images.githubusercontent.com/47480030/150304108-eb389685-b6b0-4e05-b888-cdf997c48209.png)

**Comment by mgechev** [comment]
Would you open a PR to remove it?

**Comment by GregoireLgt** [comment]
Yes of course !

**Comment by GregoireLgt** [comment]
@mgechev here is the PR here : https://github.com/angular/angular-update-guide/pull/186

Regards,
