### ISSUE TITLE
version 8 to 9: Incorrectly recommending use of ng-form instead of ngForm

### ISSUE THREAD

**Issue by jdhines** [angular/angular-update-guide#66]
The [8-to-9 guide](https://update.angular.io/#8.2:9.0l3) states:

> If you use ngForm element selector to create Angular Forms, you should instead use ng-form.

But if I replace

`<form #my-form="ngForm">`

with 

`<form #my-form="ng-form">`

then you get the error

> There is no directive with "exportAs" set to "ng-form"

Seems like this instruction should be removed, as even the [documentation](https://angular.io/guide/forms#the-ngform-directive) for v9 says to use `ngForm`.

Unless I'm misunderstanding what the migration instruction is actually saying?

**Comment by gallagherrchris** [comment]
This is referring to the selector.

An example would be:
```
<!-- Deprecated -->
<ngForm></ngForm>
```

```
<!-- Current -->
<ng-form></ng-form>
```

Here is a link to valid selectors for utilizing forms: https://angular.io/api/forms/NgForm#selectors
