### ISSUE TITLE
Moving to Angular organization

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-update-guide#91]
@StephenFluin Do you have a plan to move `update-angular-guide` to the Angular official GitHub org? 
This personal repository doesn’t look official-ish. Are there any blockers?

**Comment by StephenFluin** [comment]
The main blocker is that moving it has good longer term benefits, but not a
lot of shorter term benefits, so it generally doesn't get prioritized.

I'll also say the code quality of the work I've done probably isn't up to
the same standard as the rest of angular/angular (architecture, testing),
as this started as a skunkworks project, so all of that would need to be
fixed. This would also increase the work for the team on DevOps, whereas
Minko and I can manage the tool right now and it meets the needs of most
folks.

**Comment by lacolaco** [comment]
I understood. 

> I'll also say the code quality of the work I've done probably isn't up to
the same standard as the rest of angular/angular

Agreed. Especially, i18n feature I've implemented is not polished enough. I think the official `@angular/localize` can be applied to this application. I'd like to keep contributing to getting it better.

**Comment by mgechev** [comment]
Done :)
